### ISSUE TITLE
PRIDE has broken itself, again

### ISSUE THREAD

**Issue by lgatto** [lgatto/rpx#17]
1. Looking at PXD000001, it used to be at [ftp.pride.ebi.ac.uk/pride/data/archive/2012/03/PXD000001](http://ftp.pride.ebi.ac.uk/pride/data/archive/2012/03/PXD000001), but now it's **404 Not Found**.
2. If I navigate there through the [website](https://www.ebi.ac.uk/pride/archive/projects/PXD000001), it points to [http://ftp.ebi.ac.uk/pride-archive/2012/03/PXD000001/](http://ftp.ebi.ac.uk/pride-archive/2012/03/PXD000001/). 
3. But, their own internal [metadata](https://www.ebi.ac.uk/pride/ws/archive/v2/projects/PXD000001) points to the old and broken URL

![2021-11-02-145029_727x252_scrot](https://user-images.githubusercontent.com/384198/139860139-30ced189-a113-49e7-9fc2-71639c9560ea.png)

WTF?!?

**Comment by lgatto** [comment]
This will apparently still last for a month, but no indication of what/how things will work/be fixed thereafter.

**Comment by Jasper472** [comment]
Is there a workaround for this issue?
I'd like to run through the code on https://www.bioconductor.org/packages/release/data/experiment/vignettes/RforProteomics/inst/doc/RProtVis.html#3_The_MA_plot_example and test it with PXD000001, before I want to apply it to my own data.

**Comment by lgatto** [comment]
I haven't received any information of the PRIDE manager, so I don't know if I should implement a fix on my side, or it they are going to address the inconsistency on their side. 

You should be able to read the data with 
```r
readMzTabData("F063721.dat-mztab.txt", what = "PEP")
```

If that doesn't work, please open an issue on [`MSnbase`](https://github.com/lgatto/MSnbase/issues), share the file, and I'll have a look.

**Comment by Jasper472** [comment]
Thank you so much, I can read the data now but the next line causes an error. I opened and issue on MSnbase for it.

**Comment by lgatto** [comment]
A temporary fix is available at 

```
remotes::install_github("lgatto/rpx", ref = "issue17")
```

The NEWS file says:

- Provide fix for PRIDE migration and annotation discrepancies (see
  issue #17). This fix will however lead to re-downloading some cached
  files due to different URLs. The fix might only be temporary, based
  on if/how PRIDE will address their inconsistencies.

**Comment by lgatto** [comment]
PRIDE is now moving back to the old URL, but both should remain functional.
