### ISSUE TITLE
Error in file(file, "rt") ...

### ISSUE THREAD

**Issue by HijaziHassan** [lgatto/rpx#18]
Hi Igatto,

Whenever I try to run this code
`px1 <- PXDataset("PXD000001")`

It tries to fetch the data ..

`Querying ProteomeXchange for PXD000001.`

but .. it finally throws an error ...
```
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: In file(file, "rt") :
  the 'wininet' method of url() is deprecated for ftp:// URLs
2: In file(file, "rt") :
  InternetOpenUrl failed: 'A connection with the server could not be established
'
```

Is still a problem of the database? 
Thanks

**Comment by lgatto** [comment]
Yes, that's because PRIDE is broken (see #17 and [here](https://twitter.com/lgatt0/status/1455528118291255300) on twitter).

**Comment by HijaziHassan** [comment]
Ok, thank you very much.
