### ISSUE TITLE
Repository PXD000001 can't be loaded using PXDataset() function

### ISSUE THREAD

**Issue by JorgeVindelAlfageme** [lgatto/rpx#19]
Hi:
I've tried to download the repository "PXD000001" using the command `px1 <- PXDataset("PXD000001")`. I'm currently using R version 4.1.2 along with the rpx package. When I execute the command, the next error message pops up:
> Querying ProteomeXchange for PXD000001.
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: In file(file, "rt") :
  the 'wininet' method of url() is deprecated for ftp:// URLs
> 2: In file(file, "rt") : InternetOpenUrl failed: ''

How can I solve this problem? Can I load this repository by any other mean? Thanks in advance.

**Comment by lgatto** [comment]
Yes, this is very irritating - PRIDE has been broken for some time now (see #17 for details).

Unfortunately, PRIDE isn't providing and update on the situation and how or when it will be resolved. I have no idea whether I need to fix it on my side, or if they will fix it on theirs. @ypriverol any updates?

**Comment by JorgeVindelAlfageme** [comment]
For now, until this problem is solved, I'm using one of the R libraries you created, @lgatto, to import the data I need into my computer. The R library I'm talking about is "PXD000001". This library allows me to download the mentioned data because I'm new to proteomics and I'm learning how to use the library "RforProteomics" that has its own tutorial in bioconductor: https://www.bioconductor.org/packages/release/data/experiment/vignettes/RforProteomics/inst/doc/RforProteomics.html
Since in this page it is told the data I need are example files that also can be obtained using "PXD000001", I'll stick to that until the function `PXDataset()` can be used again. Good to know you foresaw that this kind of problem could occur so you created other repositpory as a library, @lgatto!

**Comment by lgatto** [comment]
Yes, the PXD00001 data is also available in the [msdata]([url](https://bioconductor.org/packages/release/data/experiment/html/msdata.html)) package. 

If you want to learn about proteins and MS in R/Bioc, I would suggest the following [book](https://rformassspectrometry.github.io/docs/) that is much more up-to-date.

**Comment by JorgeVindelAlfageme** [comment]
I'll take that book into account. Thanks!

**Comment by lgatto** [comment]
A temporary fix is available at 
```
remotes::install_github("lgatto/rpx", ref = "issue17")
```
Closing this issue for now but feel free to re-open it if you still have issues.
