### ISSUE TITLE
Error in downloading a record.

### ISSUE THREAD

**Issue by moghbaie** [lgatto/rpx#3]
I'm trying to get xml data from PRIDE and I'm getting this error:
px <- PXDataset("PXD002412")
pxfiles(px)
mzf <- pxget(px, pxfiles(px)[6])

Downloading 1 file
trying URL 'ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2015/07/PXD002412/interact-HG_130628_84_OT3_WDR5_IB001_1_293.prot.xml'
Error in download.file(urls[i], toget[i], ...) : 
  cannot open URL 'ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2015/07/PXD002412/interact-HG_130628_84_OT3_WDR5_IB001_1_293.prot.xml'
In addition: Warning message:
In download.file(urls[i], toget[i], ...) :
  InternetOpenUrl failed: 'The login request was denied
'

**Comment by lgatto** [comment]
Thank you very much for the report, @moghbaie. I think this was a temporary glitch, as I managed to run the chunk. 

```r
> px <- PXDataset("PXD002412")
> px
Object of class "PXDataset"
 Id: PXD002412 with 1037 files
 [1] 'FINV_uniprot_sprot_human_BSA_TRY_BCN_GFP_TEV_062911.fasta' ... [1037] 'interact-JO_120120_OT3_TRIM28-P004.prot.xml'
 Use 'pxfiles(.)' to see all files.
> pxfiles(px)[6]
[1] "GR_130124_14_OT3_SIRT5_IB001_1_HEK293.mzXML"
> mzf <- pxget(px, pxfiles(px)[6])
Downloading 1 file
trying URL 'ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2015/07/PXD002412/GR_130124_14_OT3_SIRT5_IB001_1_HEK293.mzXML'
Content type 'unknown' length 278025154 bytes (265.1 MB)
==================================================
> library(mzR)
Loading required package: Rcpp
> openMSfile(mzf)
Mass Spectrometry file handle.
Filename:  GR_130124_14_OT3_SIRT5_IB001_1_HEK293.mzXML 
Number of scans:  28561 
```

Still thanks for reporting it, as there have been some issues in the past with the server at the ISB and reports like this might help them to identify when/what goes wrong.

I'll close the issue, but do not hesitate to re-open it if you still hit issues.
