### ISSUE TITLE
Wrong ftp URL in xml of data 

### ISSUE THREAD

**Issue by lgatto** [lgatto/rpx#5]
In the xml of a data, cvParam PRIDE:0000411 used to provide the ftp URL to the data. For example
```r
> library(rpx)
> px <- PXDataset("PXD000001")
> pxurl(px)
 [1] "ftp://ftp.pride.ebi.ac.uk/2012/03/PXD000001"
```
which now throws and error in downstream processing. The data is now at at different URL:
``` 
ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2012/03/PXD000001/
```

**Comment by lgatto** [comment]
@ypriverol - could you update me here whenever there's news regarding this issue. The `rpx` package is failing due to this and I will need to fix this rather early than late.

**Comment by ypriverol** [comment]
I will update you when the issue is fixed. We have some other network issues at EBI we are trying to deal with. I will keep you posted.

**Comment by lgatto** [comment]
Any news, @ypriverol ?

**Comment by lgatto** [comment]
@ypriverol - any news on this? If this situation is to stay for any undetermined time, could you please let me know so that I can take other measures to sort out the resulting errors on my end.

**Comment by ypriverol** [comment]
We are still struggling to Sync our repo with ProtemeXchange. We are trying to solve the issues but I can not give you a date.

**Comment by lgatto** [comment]
Ok, thank you for the update.

**Comment by ebrombacher** [comment]
Hi,

In some cases, such as for PXD001584, the location path in the xml includes "pride/data/archive" : 

```
<FullDatasetLink>
            <cvParam cvRef="PRIDE" accession="PRIDE:0000411" name="Dataset FTP location" value="ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2015/01/PXD001584"/>
</FullDatasetLink>
```

So after the update in the resulting url "pride/data/archive" is duplicated:
```
> px <- PXDataset("PXD001584")
> pxurl(px)
[1] "ftp://ftp.pride.ebi.ac.uk/pride/data/archive/pride/data/archive/2015/01/PXD001584"
```
Cheers

**Comment by lgatto** [comment]
Thank you @ebrombacher.

@ypriverol - any updates on this issue?

**Comment by ebrombacher** [comment]
Thank you! Are there any news on this, @lgatto @ypriverol?

**Comment by ypriverol** [comment]
@lgatto @ebrombacher We have fixed the problem inside pride but we are trying to push into ProteomeXchange the schema has been changed and we are now trying to work with them. This has priority in PRIDE but it will take a couple of more weeks to be fixed.

**Comment by lgatto** [comment]
Thank you @ypriverol - please keep us posted here an I'll update the package accordingly.

**Comment by lgatto** [comment]
@ebrombacher in the meantime, if you install the github version (1.23.1), you will be able to
```
> px <- PXDataset("PXD001584")
> pxurl(px)
[1] "ftp://ftp.pride.ebi.ac.uk/pride/data/archive/pride/data/archive/2015/01/PXD001584"
> rpx:::apply_fix_issue_5(FALSE)
> pxurl(px)
[1] "ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2015/01/PXD001584"
```

**Comment by ebrombacher** [comment]
@lgatto @ypriverol Great, thanks so much for your help!

**Comment by ebrombacher** [comment]
@lgatto Perfect, thank you!
